const alliances = [
  {
    id: 1,
    koreanName: "빗썸",
    englishName: "Bithumb",
    membership: "Travel Rule Member",
    imgSrc: "bithumb.jpg",
  },
  {
    id: 2,
    koreanName: "코인원",
    englishName: "Coinone",
    membership: "Travel Rule Member",
    imgSrc: "coinone.png",
  },
  {
    id: 3,
    koreanName: "코빗",
    englishName: "Korbit",
    membership: "Travel Rule Memeber",
    imgSrc: "korbit.jpg",
  },
  {
    id: 4,
    koreanName: "큐비트",
    englishName: "QBIT",
    membership: "Travel Rule Memeber",
    imgSrc: "qbit.jpg",
  },
  {
    id: 5,
    koreanName: "한빗코",
    englishName: "Hanbitco",
    membership: "Travel Rule Memeber",
    imgSrc: "hanbitco.webp",
  },
  {
    id: 6,
    koreanName: "한국디지털자산수탁",
    englishName: "KDAC",
    membership: "Travel Rule Memeber",
    imgSrc: "kdac.png",
  },
  {
    id: 7,
    koreanName: "헥슬란트",
    englishName: "Hexlant",
    membership: "Travel Rule Memeber",
    imgSrc: "hexlant.png",
  },
  {
    id: 8,
    koreanName: "카르도",
    englishName: "Cardo",
    membership: "Travel Rule Memeber",
    imgSrc: "cardo.png",
  },
  {
    id: 9,
    koreanName: "비트프론트",
    englishName: "Bitfront",
    membership: "Travel Rule Memeber",
    imgSrc: "bitfront.png",
  },
  {
    id: 10,
    koreanName: "코인엔코인",
    englishName: "Coin&Coin",
    membership: "Travel Rule Memeber",
    imgSrc: "coinncoin.png",
  },
  {
    id: 11,
    koreanName: "한국디지털에셋",
    englishName: "KODA",
    membership: "Travel Rule Memeber",
    imgSrc: "koda.png",
  },
  {
    id: 12,
    koreanName: "후오비글로벌",
    englishName: "Huobi Global",
    membership: "Travel Rule Memeber",
    imgSrc: "huobi-global.jpeg",
  },
  {
    id: 13,
    koreanName: "빙엑스",
    englishName: "BingX",
    membership: "Travel Rule Memeber",
    imgSrc: "bingx.png",
  },
  {
    id: 14,
    koreanName: "페이프로토콜",
    englishName: "Payprotocol",
    membership: "Travel Rule Memeber",
    imgSrc: "payprotocol.png",
  },
  {
    id: 15,
    koreanName: "코인빗",
    englishName: "Coinbit",
    membership: "Travel Rule Memeber (On-boarding)",
    imgSrc: "coinbit.png",
  },
  {
    id: 16,
    koreanName: "비트겟",
    englishName: "Bitget",
    membership: "Travel Rule Memeber",
    imgSrc: "bitget.png",
  },
  {
    id: 17,
    koreanName: "지닥",
    englishName: "GDAC",
    membership: "Travel Rule Memeber (On-boarding)",
    imgSrc: "gdac.svg",
  },
  // {
  //   id: 18,
  //   koreanName: "코인플러그",
  //   englishName: "Coinplug",
  //   membership: "Travel Rule Memeber",
  //   imgSrc: "coinplug.png",
  // },
  {
    id: 19,
    koreanName: "오아시스",
    englishName: "Oasis",
    membership: "Travel Rule Memeber",
    imgSrc: "oasis.png",
  },
  {
    id: 20,
    koreanName: "웁살라시큐리티",
    englishName: "Uppsala Security",
    membership: "Associate Member",
    imgSrc: "uppsalasecurity.png",
  },
  {
    id: 21,
    koreanName: "갤럭시아메타버스",
    englishName: "Galaxia Metaverse",
    membership: "Associate Memeber",
    imgSrc: "galaxiametaverse.png",
  },
  {
    id: 22,
    koreanName: "크립토텍스",
    englishName: "Cryptotax",
    membership: "Associate Memeber",
    imgSrc: "cryptotax.png",
    padding: 8,
  },
  {
    id: 23,
    koreanName: "로똔다",
    englishName: "Rotonda",
    membership: "Associate Memeber",
    imgSrc: "rotonda.png",
  },
  {
    id: 24,
    koreanName: "키인사이드",
    englishName: "Keyinside",
    membership: "Associate Memeber",
    imgSrc: "keyinside.png",
  },
  {
    id: 25,
    koreanName: "빗썸메타",
    englishName: "BithumbMETA",
    membership: "Associate Memeber",
    imgSrc: "bithumbmeta.png",
  },
  {
    id: 26,
    koreanName: "팔라",
    englishName: "PALA",
    membership: "Associate Memeber",
    imgSrc: "pala.png",
  },
  {
    id: 27,
    koreanName: "트랙체인",
    englishName: "Trackchain",
    membership: "Associate Memeber",
    imgSrc: "trackchain.png",
  },
  {
    id: 28,
    koreanName: "베리파이바스프",
    englishName: "VerifyVASP",
    membership: "Travel Rule Member",
    imgSrc: "verifyvasp.png",
  },
];

export default alliances;
